on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: pixelcontainer.azurecr.io
        username: ${{ secrets.acr_pixelcontainer_username }}
        password: ${{ secrets.acr_pixelcontainer_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t pixelcontainer.azurecr.io/pixelakscontainer:${{ github.sha }}
        docker push pixelcontainer.azurecr.io/pixelakscontainer:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_pixelakscontainer_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep pixelakscontainer5c16 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace pixelakscontainer5c16`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: pixelakscontainer5c16
        container-registry-url: pixelcontainer.azurecr.io
        container-registry-username: ${{ secrets.acr_pixelcontainer_username }}
        container-registry-password: ${{ secrets.acr_pixelcontainer_password }}
        secret-name: pixelakscontdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: pixelakscontainer5c16
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          pixelcontainer.azurecr.io/pixelakscontainer:${{ github.sha }}
        imagepullsecrets: |
          pixelakscontdockerauth